# Generated by Django 3.2 on 2021-05-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universe',
            name='date_foundation',
            field=models.DateTimeField(),
        ),
    ]
